services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "tiny11"
      RAM_SIZE: "10G"
      CPU_CORES: "3"
      DISK_SIZE: "28G"
      USERNAME: "User"
      PASSWORD: "Admin@1234"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    stop_grace_period: 2m
    restart: on-failure

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: on-failure

  guacamole:
    image: jwetzell/guacamole
    container_name: guacamole
    environment:
      GUACD_HOST: guacd
      RDP_HOST: windows
      RDP_PORT: "3389"
      RDP_USERNAME: "User"
      RDP_PASSWORD: "Admin@1234"
    ports:
      - "8080:8080"
    depends_on:
      - windows
      - guacd
    restart: on-failure
